### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by ahmadzainuririzaldi** [openkoda/openkoda#17]
I followed the instructions, and stuck in step 4

detail error is provided in screenshot

![image](https://github.com/user-attachments/assets/9b9f9cb1-eee1-48eb-861a-15e094c9a0a7)

please help me...

**Comment by arekdrysch** [comment]
Hello @ahmadzainuririzaldi,

Can you please provide answers for these questions:

1. Is the openkoda.jar file present in the `C:\Users\HP` folder? If yes, what is the size of the file?
2. What java version do you use? (`java -version` command)
3. Some anti-malware software put executable files (including jar files) into quarantine. Can you check if that's the case?
Regards,
Arek

**Comment by ahmadzainuririzaldi** [comment]
1. I'm sorry, this is the right path of my openkoda(check Screen Capture)
2. java version 20
3. the only anti malware on my computer is windows defender, and i turned it off

![image](https://github.com/user-attachments/assets/e56a0fd6-18e1-4634-a923-ecc43e7fe957)

**Comment by arekdrysch** [comment]
Thank you for the answers.

There are a few points here:

1. Currently we support Java 17. As for now we don't support Java 20 (we plan to support Java 21 LTS in the nearest future).
2. In order to biuld openkoda.jar file you need to build it with Maven.  Using this command: `mvn -f openkoda/pom.xml clean install spring-boot:repackage -DskipTests` . After the build the file should appear in openkoda/build/ directory. It's name may be something like `openkoda-1.5.2-SNAPSHOT-EXEC.jar` (version may differ). This is the filename you should use.

Thank you for posting this issue - this will help up improve our documentation, so that it's more clear.

**Comment by ahmadzainuririzaldi** [comment]
thank's for your help sir

the application has been installed successfully on my computer

**Comment by ahmadzainuririzaldi** [comment]
thank's for your help sir

the application has been installed successfully on my computer
